CC = g++
OPT = -Wall

all: test_binary_tree phone_book

test_binary_tree: 
	$(CC) $(OPT) test_binary_tree.cpp -o test_binary_tree

phone_book:
	$(CC) $(OPT) phone_book.cpp main.cpp -o phone_book

clean:
	rm -f test_binary_tree phone_book

